version: '3'
services:
  server:
    build: .
    environment:
      NODE_ENV: production
    ports:
      - '8080:8080'
    links:
      - 'mongo:mongo'
  mongo:
    image: mongo:3.4.18-jessie
    ports:
      - '27017:27017'
